server:
  port: 2000

spring:
  datasource:
    username: root
    password: 970415
    url: jdbc:mysql://localhost:3306/project_gmall?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

  dubbo:
    application:
      name: user-service         #微服务名字
    registry:
      address: 192.168.126.128:2181  #zookeeper地址
      protocol: zookeeper            #注册中心类型
    base-package: com.atguigu.gmall  #包扫描
    protocol:                       #分布式 固定为 dubbo
      name: dubbo

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

